apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: apache
    app.kubernetes.io/name: apache
  name: apache
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: apache
    app.kubernetes.io/name: apache
    app.kubernetes.io/part-of: apache
    app.kubernetes.io/version: 2.4
  name: apache
  namespace: apache
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: apache
    app.kubernetes.io/name: apache
    app.kubernetes.io/part-of: apache
    app.kubernetes.io/version: 2.4
  name: apache
  namespace: apache
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: apache
    app.kubernetes.io/name: apache
    app.kubernetes.io/part-of: apache
    app.kubernetes.io/version: 2.4
  name: apache
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - secrets
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: apache
    app.kubernetes.io/name: apache
    app.kubernetes.io/part-of: apache
    app.kubernetes.io/version: 2.4
  name: apache
  namespace: apache
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apache
subjects:
- kind: ServiceAccount
  name: apache
  namespace: apache
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: apache
    app.kubernetes.io/name: apache
    app.kubernetes.io/part-of: apache
    app.kubernetes.io/version: 2.4
  name: apache
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apache
subjects:
- kind: ServiceAccount
  name: apache
  namespace: apache
---
apiVersion: v1
data:
  server-config: |
    ServerRoot "/usr/local/apache2"
    Listen 80
    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule http_module modules/mod_http.so
    LoadModule mime_module modules/mod_mime.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule env_module modules/mod_env.so
    LoadModule headers_module modules/mod_headers.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule alias_module modules/mod_alias.so
    <Directory />
        AllowOverride none
        Require all denied
    </Directory>
    DocumentRoot "/usr/local/apache2/htdocs"
    <Directory "/usr/local/apache2/htdocs">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
    ErrorLog "/proc/self/fd/2"
    LogLevel warn
    CustomLog "/proc/self/fd/1" combined
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: apache
    app.kubernetes.io/name: apache
    app.kubernetes.io/part-of: apache
    app.kubernetes.io/version: 2.4
  name: apache-config
  namespace: apache
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: apache
    app.kubernetes.io/name: apache
    app.kubernetes.io/part-of: apache
    app.kubernetes.io/version: 2.4
  name: apache-service
  namespace: apache
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: apache
    app.kubernetes.io/name: apache
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: apache
    app.kubernetes.io/name: apache
    app.kubernetes.io/part-of: apache
    app.kubernetes.io/version: 2.4
  name: apache-deployment
  namespace: apache
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: apache
      app.kubernetes.io/name: apache
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/instance: apache
        app.kubernetes.io/name: apache
        app.kubernetes.io/part-of: apache
        app.kubernetes.io/version: 2.4
    spec:
      containers:
      - image: httpd:2.4
        name: apache
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/conf/httpd.conf
          name: apache-config
          subPath: server-config
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
      volumes:
      - configMap:
          name: apache-config
        name: apache-config
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: apache
      terminationGracePeriodSeconds: 30
